CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50),
    mall_type VARCHAR(255),
    aladin_category_id INTEGER NOT NULL,
    CONSTRAINT uk_category_mall_type_name UNIQUE (mall_type, category_name)
);

CREATE INDEX idx_category_malltype_name
    ON category (mall_type, category_name);

CREATE TABLE book (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13 VARCHAR(13),
    title VARCHAR(1000),
    author VARCHAR(1500),
    publisher VARCHAR(1500),
    publication_date VARCHAR(255),
    pages INTEGER,
    description TEXT,
    cover_image_key VARCHAR(2000),
    aladin_link TEXT,
    source_type VARCHAR(255),
    created_by_user_id BIGINT,
    category_id BIGINT,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_book_category
        FOREIGN KEY (category_id) REFERENCES category (category_id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255),
    goal SMALLINT,
    role VARCHAR(255),
    provider VARCHAR(255),
    provider_id VARCHAR(255),
    email VARCHAR(255),
    chat_usage SMALLINT,
    deleted_at TIMESTAMP(6),
    profile_image_key TEXT,
    nick_name VARCHAR(255),
    onboarding_completed_at TIMESTAMP(6),
    preferred_category_id BIGINT,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_users_preferred_category
        FOREIGN KEY (preferred_category_id) REFERENCES category (category_id)
);

CREATE TABLE search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    search_type VARCHAR(20) NOT NULL,
    user_id BIGINT NOT NULL,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_search_history_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_search_history_user_type
    ON search_history (user_id, search_type);

CREATE INDEX idx_search_history_user_keyword_type
    ON search_history (user_id, keyword, search_type);

CREATE TABLE library (
    library_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_status VARCHAR(255),
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    started_at DATE,
    ended_at DATE,
    focus_sec BIGINT,
    page INTEGER NOT NULL,
    version BIGINT,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_library_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_library_book
        FOREIGN KEY (book_id) REFERENCES book (book_id),
    CONSTRAINT uk_library_user_book UNIQUE (user_id, book_id)
);

CREATE INDEX idx_library_user_status_id
    ON library (user_id, reading_status, library_id DESC);

CREATE TABLE themes (
    theme_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT uk_themes_name UNIQUE (name)
);

CREATE TABLE focuses (
    focus_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL,
    theme_id BIGINT NOT NULL,
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    duration_sec INTEGER,
    end_page INTEGER,
    focus_date DATE,
    started_time TIME(6),
    ended_time TIME(6),
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_focuses_library
        FOREIGN KEY (library_id) REFERENCES library (library_id),
    CONSTRAINT fk_focuses_theme
        FOREIGN KEY (theme_id) REFERENCES themes (theme_id)
);

CREATE INDEX idx_focus_library_focus_date
    ON focuses (library_id, focus_date);

CREATE TABLE records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL,
    emotion VARCHAR(255),
    content VARCHAR(255),
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_records_library
        FOREIGN KEY (library_id) REFERENCES library (library_id)
);

CREATE INDEX idx_records_library_id
    ON records (emotion, library_id DESC);

CREATE TABLE record_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT,
    image_url VARCHAR(1000),
    key VARCHAR(255),
    order_index INTEGER,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_record_images_record
        FOREIGN KEY (record_id) REFERENCES records (record_id)
);

CREATE TABLE book_timelines (
    timeline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    target_id BIGINT NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    preview_text VARCHAR(500),
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_book_timelines_library
        FOREIGN KEY (library_id) REFERENCES library (library_id)
);

CREATE INDEX idx_book_timelines_library_occurred
    ON book_timelines (library_id, occurred_at DESC, timeline_id DESC);

INSERT INTO category (mall_type, category_name, aladin_category_id)
VALUES
    ('BOOK', '가정/요리/뷰티', 1230),
    ('EBOOK', '가정/요리/뷰티', 38409),
    ('BOOK', '건강/취미/레저', 55890),
    ('EBOOK', '건강/취미/레저', 56388),
    ('BOOK', '경제경영', 170),
    ('EBOOK', '경제경영', 38398),
    ('BOOK', '고전', 2105),
    ('EBOOK', '고전', 38414),
    ('BOOK', '과학', 987),
    ('EBOOK', '과학', 38405),
    ('BOOK', '만화', 2551),
    ('EBOOK', '만화', 38416),
    ('BOOK', '사회과학', 798),
    ('EBOOK', '사회과학', 38404),
    ('BOOK', '어린이', 1108),
    ('EBOOK', '어린이', 38406),
    ('BOOK', '에세이', 55889),
    ('EBOOK', '에세이', 56387),
    ('BOOK', '여행', 1196),
    ('EBOOK', '여행', 38408),
    ('BOOK', '역사', 74),
    ('EBOOK', '역사', 38397),
    ('BOOK', '외국어', 1322),
    ('EBOOK', '외국어', 38411),
    ('BOOK', '유아', 13789),
    ('EBOOK', '유아', 38424),
    ('BOOK', '인문학', 656),
    ('EBOOK', '인문학', 38403),
    ('BOOK', '자기계발', 336),
    ('EBOOK', '자기계발', 38400),
    ('BOOK', '종교/역학', 1237),
    ('EBOOK', '종교/역학', 38410),
    ('BOOK', '좋은부모', 2030),
    ('EBOOK', '좋은부모', 38413),
    ('BOOK', '청소년', 1137),
    ('EBOOK', '청소년', 38407),
    ('BOOK', '컴퓨터/모바일', 351),
    ('EBOOK', '컴퓨터/모바일', 38401),
    ('BOOK', '전문서적', 8257),
    ('EBOOK', '전문서적', 38422),
    ('BOOK', '예술/문화', 517),
    ('EBOOK', '예술/문화', 38402),
    ('BOOK', '소설/시/희곡', 1),
    ('EBOOK', '소설/시/희곡', 38396)
ON CONFLICT (mall_type, category_name)
DO UPDATE SET aladin_category_id = EXCLUDED.aladin_category_id;
