CREATE TABLE book_view_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    created_date TIMESTAMP(6),
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_book_view_history_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_book_view_history_book
        FOREIGN KEY (book_id) REFERENCES book (book_id),
    CONSTRAINT uk_book_view_history_user_book
        UNIQUE (user_id, book_id)
);

CREATE INDEX idx_book_view_history_user_modified
    ON book_view_history (user_id, modified_date DESC, id DESC);
